### ISSUE TITLE
xformers not installed

### ISSUE THREAD

**Issue by faraday** [tencent-ailab/V-Express#7]
When running the script after following the instructions, I get **xformers** not available error.
```
Loaded weights of Reference Net from ./model_ckpts/v-express/reference_net.pth.
Loaded weights of Denoising U-Net from ./model_ckpts/v-express/denoising_unet.pth.
Loaded weights of Denoising U-Net Motion Module from ./model_ckpts/v-express/motion_module.pth.
Loaded weights of V-Kps Guider from ./model_ckpts/v-express/v_kps_guider.pth.
Loaded weights of Audio Projection from ./model_ckpts/v-express/audio_projection.pth.
Traceback (most recent call last):
  File "/content/V-Express/inference.py", line 275, in <module>
    main()
  File "/content/V-Express/inference.py", line 171, in main
    raise ValueError("xformers is not available. Make sure it is installed correctly")
ValueError: xformers is not available. Make sure it is installed correctly
```

Since the version is not listed in the pip package list in your instructions and installing the latest leads to incompatibilities, could you share the xformers package version you used in the project?

**Comment by faraday** [comment]
I'm guessing `xformers==0.0.19` compatible, right?

**Comment by faraday** [comment]
It ran just fine with:
```
!pip install xformers==0.0.19
!pip install av==10.0.0
```

**Comment by xinxiaozhe12345** [comment]
> It ran just fine with:
> 
> ```
> !pip install xformers==0.0.19
> !pip install av==10.0.0
> ```

Thanks so much, buddy

**Comment by faraday** [comment]
seems like `xformers==0.0.20` more suitable (because of torch 2.0.1)
